// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY7IG0bZwZEqUxrlN5VrsJGeGLjflPC_U',
    appId: '1:740150444954:web:cbf9721e05d828c1bfb023',
    messagingSenderId: '740150444954',
    projectId: 'study-app-5c7c4',
    authDomain: 'study-app-5c7c4.firebaseapp.com',
    databaseURL: 'https://study-app-5c7c4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'study-app-5c7c4.appspot.com',
    measurementId: 'G-PPYLHP9KG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY_8cB1H8VBpq53g11pw-Lhb8MBAtXTPk',
    appId: '1:740150444954:android:3168b52703e30239bfb023',
    messagingSenderId: '740150444954',
    projectId: 'study-app-5c7c4',
    databaseURL: 'https://study-app-5c7c4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'study-app-5c7c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV9hbpLkl_KZWx2vRJ5rCupAnfdMnn7Xo',
    appId: '1:740150444954:ios:e1d376bb196a42bebfb023',
    messagingSenderId: '740150444954',
    projectId: 'study-app-5c7c4',
    databaseURL: 'https://study-app-5c7c4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'study-app-5c7c4.appspot.com',
    iosClientId: '740150444954-ljcdo6lo2usl7g8k85g7lngijne5d9iv.apps.googleusercontent.com',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV9hbpLkl_KZWx2vRJ5rCupAnfdMnn7Xo',
    appId: '1:740150444954:ios:e1d376bb196a42bebfb023',
    messagingSenderId: '740150444954',
    projectId: 'study-app-5c7c4',
    databaseURL: 'https://study-app-5c7c4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'study-app-5c7c4.appspot.com',
    iosClientId: '740150444954-ljcdo6lo2usl7g8k85g7lngijne5d9iv.apps.googleusercontent.com',
    iosBundleId: 'com.example.testProject',
  );
}
